<?php
session_start();
if (!isset($_SESSION['lang']) || !in_array($_SESSION['lang'], ['en', 'ru'])) {
    $_SESSION['lang'] = 'ru';
}
if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'ru'])) {
    $_SESSION['lang'] = $_GET['lang'];
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}
require_once "languages/" . $_SESSION['lang'] . ".php";
?>
<!DOCTYPE html>
<html lang="<?= htmlspecialchars($_SESSION['lang']) ?>">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?= $_SESSION['lang'] === 'ru' ? 'Геральт из Ривии — Биография' : 'Geralt of Rivia — Biography' ?></title>
<link rel="stylesheet" href="css/style.css"><link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
<style>
header.gc-cover{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);align-items:center;gap:40px;max-width:1160px;margin:0 auto;padding:70px 24px 32px;background:transparent;color:#eee;text-align:left}
header.gc-cover::before{display:none}header.gc-cover img{display:block;max-width:100%;width:auto;height:auto;max-height:72vh;object-fit:contain;margin:auto;border-radius:8px}
header.gc-cover .header-content{padding:0;margin:0;text-align:left}header.gc-cover h1{font-size:clamp(2rem,4vw,3.6rem);line-height:1.2;color:#e0bd77}header.gc-cover p{font-size:1.2rem;color:#ddd}
@media(max-width:650px){header.gc-cover{grid-template-columns:1fr;gap:24px;padding:72px 18px 28px}header.gc-cover img{max-height:62vh}header.gc-cover .header-content{text-align:center}header.gc-cover h1{font-size:2rem}}

body.gb-page header.parallax{height:440px;min-height:320px;background-attachment:scroll}
.gb-page .header-content{max-width:900px}.gb-page .header-content h1{margin-bottom:12px}
.gb-page main{max-width:1160px;margin:36px auto;padding:0 24px}
.gb-page .gb-jumps{position:static;background:transparent;box-shadow:none;display:flex;flex-wrap:wrap;gap:10px;margin-bottom:28px}
.gb-page .gb-jumps a,.gb-page .gb-cta{display:inline-block;color:#e7c98f;text-decoration:none;border:1px solid #716044;border-radius:6px;padding:10px 16px}
.gb-page a:focus-visible,.gb-page summary:focus-visible{outline:3px solid #e7c98f;outline-offset:4px}
.gb-page .gb-note{border-left:3px solid #c0a062;padding:12px 18px;background:#242320;color:#cfc6b4;font:15px/1.7 Arial,sans-serif;margin-bottom:40px}
.gb-page section{scroll-margin-top:110px;margin-bottom:64px}.gb-page h2{text-align:left;font-size:clamp(1.6rem,4vw,2.2rem)}.gb-page h2::after{margin:12px 0;width:56px}
.gb-page .gb-intro{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:36px;align-items:center}
.gb-page .gb-portrait{display:block;width:100%;max-height:470px;object-fit:cover;border-radius:12px;border:1px solid #484032}
.gb-page main p,.gb-page dd{font-family:Arial,sans-serif;font-size:16px;line-height:1.85;color:#d4d0c9}
.gb-page .gb-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:24px}.gb-page dt{font:12px/1.5 Arial,sans-serif;color:#c0a062;margin-bottom:5px}.gb-page dd{margin:0;font-size:14px}
.gb-page .gb-steps{list-style:none;counter-reset:steps;border-left:1px solid #716044;margin-left:18px;padding-left:30px}
.gb-page .gb-steps li{position:relative;padding:0 0 30px 12px;counter-increment:steps}.gb-page .gb-steps li::before{content:counter(steps);position:absolute;left:-49px;top:0;border:1px solid #c0a062;background:#1a1a1a;border-radius:50%;width:34px;height:34px;display:grid;place-items:center;color:#e7c98f}
.gb-page .gb-tag{display:block;color:#c0a062;font:12px/1.6 Arial,sans-serif;letter-spacing:.07em;margin-bottom:10px}.gb-page h3{font-size:1.45rem;margin-bottom:10px}
.gb-page .gb-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.gb-page .gb-card{border:1px solid #4a4031;border-top:3px solid #b1945a;border-radius:8px;padding:24px;background:#242320;min-width:0}.gb-page .gb-card p:last-child{margin-bottom:0}
.gb-page details{border:1px solid #4a4031;border-radius:8px;background:#242320;padding:20px}.gb-page summary{cursor:pointer;color:#e7c98f;padding:5px;font:16px/1.6 Arial,sans-serif}.gb-page .gb-games{display:grid;gap:24px;padding-top:24px}.gb-page .gb-games article{padding-top:20px;border-top:1px solid #4a4031}
.gb-page .gb-source{margin-top:28px;font:13px/1.7 Arial,sans-serif}.gb-page .gb-source a{color:#c7b58e}.gb-page .gb-cta{margin-top:24px}
@media(max-width:760px){.gb-page .gb-intro{grid-template-columns:1fr}.gb-page .gb-portrait{max-height:370px;object-position:center 25%}.gb-page .gb-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.gb-page .nav-menu{flex-direction:row;gap:2px}.gb-page .nav-menu li{margin:0}.gb-page .nav-menu a{font-size:14px;padding:8px}.gb-page header.parallax{height:340px}.gb-page .header-content p{font-size:1rem}.gb-page section{scroll-margin-top:130px}}
@media(max-width:480px){.gb-page main{padding:0 16px}.gb-page .gb-grid{grid-template-columns:1fr}.gb-page .gb-facts{grid-template-columns:1fr;gap:12px}.gb-page .gb-card{padding:20px}.gb-page .gb-jumps a{font-size:14px}.gb-page .header-content h1{font-size:2.1rem}}

header.gc-cover{position:relative;display:flex;align-items:center;justify-content:center;width:100%;max-width:none;height:100vh;height:100svh;min-height:360px;margin:0;padding:24px;background:#080909;overflow:hidden;text-align:center;isolation:isolate}
header.gc-cover img{position:absolute;inset:0;display:block;width:100%;height:100%;max-width:none;max-height:none;margin:0;border-radius:0;object-fit:cover;object-position:center 25%;z-index:-2}
header.gc-cover::before{content:"";display:block;position:absolute;inset:0;background:rgba(0,0,0,.3);z-index:-1;pointer-events:none}
header.gc-cover .header-content{position:relative;width:100%;max-width:1100px;margin:0 auto;padding:20px;text-align:center}
header.gc-cover h1{color:#fff;font-size:clamp(2rem,4.5vw,4rem);line-height:1.2;text-shadow:0 2px 14px #000;margin-bottom:18px}
header.gc-cover p{color:#fff;font-size:clamp(1rem,2vw,1.5rem);text-shadow:0 2px 10px #000}
@media(max-width:650px){header.gc-cover{display:flex;padding:16px;gap:0}header.gc-cover img{max-height:none}header.gc-cover .header-content{padding:12px}}
</style></head><body class="gb-page"><div class="language-switcher"><a href="?lang=en" class="<?= $_SESSION['lang'] === 'en' ? 'active' : '' ?>" lang="en">EN</a><a href="?lang=ru" class="<?= $_SESSION['lang'] === 'ru' ? 'active' : '' ?>" lang="ru">RU</a></div>
<?php if ($_SESSION['lang'] === 'ru'): ?><header class="gc-cover"><img src="images/banners/about-cover.jpg" alt="<?= $_SESSION['lang'] === 'ru' ? 'Геральт с мечом' : 'Geralt with a sword' ?>"><div class="header-content"><h1>Геральт из Ривии</h1><p>За легендой о Белом Волке</p></div></header>
<?php require __DIR__ . '/menu.php'; ?>
<main><nav class="gb-jumps" aria-label="Геральт из Ривии"><a href="#profile">О герое</a><a href="#path">Путь ведьмака</a><a href="#people">Близкие люди</a><a href="#games">Игровая история</a></nav><p class="gb-note">Книжная основа и игровое продолжение отмечены отдельно. Ниже — завязки историй без раскрытия финалов.</p>
<section id="profile"><div class="gb-intro"><img class="gb-portrait" src="images/portraits/geralt-bio.jpg" alt="Геральт из Ривии"><div><h2>Больше, чем охотник</h2><p>Ведьмак, охотник на чудовищ и человек, которому редко удаётся остаться в стороне. Его история — не только о заказах и сражениях, но и о выборе, дружбе и семье.</p><p>Геральт зарабатывает на жизнь ведьмачьими заказами: выслеживает опасных существ, снимает проклятия и разбирается в чужих бедах. Мечи, зелья и знаки помогают ему выживать, но далеко не каждую проблему можно решить силой.</p><p>За сдержанностью и резкими ответами скрывается человек, привязанный к своим друзьям. Стремление к нейтралитету постоянно сталкивается с необходимостью защищать тех, кто ему дорог.</p><dl class="gb-facts"><div><dt>Прозвище</dt><dd>Белый Волк</dd></div><div><dt>Школа</dt><dd>Школа Волка</dd></div><div><dt>Ремесло</dt><dd>Охотник на чудовищ</dd></div></dl></div></div></section>
<section id="path"><span class="gb-tag">Книжная основа</span><h2>Путь ведьмака</h2><ol class="gb-steps"><li><span class="gb-tag">Каэр Морхен</span><h3>Обучение и испытания</h3><p>Детство Геральта связано с ведьмачьей крепостью. Подготовка, мутации и суровая дисциплина превращают его в охотника, способного противостоять чудовищам.</p></li><li><span class="gb-tag">На Большом тракте</span><h3>Цена нейтралитета</h3><p>Странствуя между городами и деревнями, Геральт встречает не только чудовищ. Заказ нередко оборачивается спором о страхе, предрассудках и человеческой жестокости.</p></li><li><span class="gb-tag">Йеннифэр и Цири</span><h3>Семья, которую выбирают</h3><p>Отношения с Йеннифэр и связь с Цири меняют его жизнь. Забота о близких становится важнее привычного одиночества и попыток держаться подальше от чужих конфликтов.</p></li></ol></section>
<section id="people"><h2>Люди, которые ему дороги</h2><p>Пять связей, без которых история Геральта была бы другой.</p><div class="gb-grid"><article class="gb-card"><span class="gb-tag">Приёмная дочь</span><h3>Цири</h3><p>Связана с Геральтом судьбой, но их отношения держатся на заботе и доверии. Для него она прежде всего семья.</p></article><article class="gb-card"><span class="gb-tag">Любовь и равный собеседник</span><h3>Йеннифэр</h3><p>Чародейка из Венгерберга. Их отношения сложны, а забота о Цири — одна из важнейших связей между ними.</p></article><article class="gb-card"><span class="gb-tag">Подруга и союзница</span><h3>Трисс Меригольд</h3><p>Чародейка, близкая Геральту и Йеннифэр. Помогает Цири в Каэр Морхене и играет заметную роль в игровой истории.</p></article><article class="gb-card"><span class="gb-tag">Друг и рассказчик</span><h3>Лютик</h3><p>Поэт и бард, сопровождающий Геральта в странствиях. Его баллады превращают приключения ведьмака в легенды.</p></article><article class="gb-card"><span class="gb-tag">Наставник</span><h3>Весемир</h3><p>Опытный ведьмак Каэр Морхена и учитель Геральта. Связывает его с крепостью, школой и другими ведьмаками.</p></article></div></section>
<section id="games"><h2>Продолжение в играх</h2><p>Игры CD PROJEKT RED развивают собственное продолжение книжной истории. Выбор игрока влияет на отношения и исходы событий.</p><details><summary>Показать завязки трёх игр · небольшие спойлеры</summary><div class="gb-games"><article><h3>The Witcher</h3><p>Геральт возвращается с утраченной памятью. Поиск ответов втягивает его в конфликты, где трудно отделить личный интерес от чужих замыслов.</p></article><article><h3>The Witcher 2: Assassins of Kings</h3><p>Ведьмак оказывается в центре политического кризиса. Ему предстоит разобраться в убийствах правителей и попытаться восстановить собственное прошлое.</p></article><article><h3>The Witcher 3: Wild Hunt</h3><p>Поиски Цири ведут Геральта через разорённые войной земли. На первый план выходят семья, старые связи и угроза Дикой Охоты.</p></article></div></details><a class="gb-cta" href="gallery.php">Открыть галерею</a><div class="gb-source">Подробнее о мире и персонажах: <a href="https://www.thewitcher.com/">The Witcher</a> · <a href="https://en.wikipedia.org/wiki/The_Witcher">The Witcher — books</a></div></section></main><?php else: ?><header class="gc-cover"><img src="images/banners/about-cover.jpg" alt="<?= $_SESSION['lang'] === 'ru' ? 'Геральт с мечом' : 'Geralt with a sword' ?>"><div class="header-content"><h1>Geralt of Rivia</h1><p>Behind the legend of the White Wolf</p></div></header>
<?php require __DIR__ . '/menu.php'; ?>
<main><nav class="gb-jumps" aria-label="Geralt of Rivia"><a href="#profile">The character</a><a href="#path">The witcher’s path</a><a href="#people">Close companions</a><a href="#games">The games</a></nav><p class="gb-note">The books and the game continuation are labelled separately. The summaries introduce the stories without revealing their endings.</p>
<section id="profile"><div class="gb-intro"><img class="gb-portrait" src="images/portraits/geralt-bio.jpg" alt="Geralt of Rivia"><div><h2>More than a monster hunter</h2><p>A witcher, a monster hunter, and a man who rarely manages to stand aside. His story is about more than contracts and battles: it is about choices, friendship, and family.</p><p>Geralt makes a living by tracking dangerous creatures, lifting curses, and dealing with other people’s troubles. Swords, potions, and signs help him survive, but force cannot solve every problem.</p><p>Behind his restrained manner and sharp replies is a man deeply attached to his friends. His wish to remain neutral repeatedly clashes with the need to protect those he cares about.</p><dl class="gb-facts"><div><dt>Known as</dt><dd>The White Wolf</dd></div><div><dt>School</dt><dd>School of the Wolf</dd></div><div><dt>Profession</dt><dd>Monster hunter</dd></div></dl></div></div></section>
<section id="path"><span class="gb-tag">Book background</span><h2>The witcher’s path</h2><ol class="gb-steps"><li><span class="gb-tag">Kaer Morhen</span><h3>Training and trials</h3><p>Geralt’s childhood is tied to the witcher stronghold. Training, mutations, and harsh discipline prepare him to face creatures that ordinary people cannot.</p></li><li><span class="gb-tag">On the road</span><h3>The cost of neutrality</h3><p>Travelling between towns and villages, Geralt encounters more than monsters. A contract can become a confrontation with fear, prejudice, and human cruelty.</p></li><li><span class="gb-tag">Yennefer and Ciri</span><h3>A family of his own</h3><p>His relationship with Yennefer and his bond with Ciri change his life. Caring for them becomes more important than solitude or staying out of other people’s conflicts.</p></li></ol></section>
<section id="people"><h2>The people closest to him</h2><p>Five relationships that shape Geralt’s story.</p><div class="gb-grid"><article class="gb-card"><span class="gb-tag">Adopted daughter</span><h3>Ciri</h3><p>Destiny connects her to Geralt, but care and trust make them a family. To him, she is far more than a prophecy.</p></article><article class="gb-card"><span class="gb-tag">Love and an equal</span><h3>Yennefer</h3><p>A sorceress from Vengerberg. Their relationship is complicated, and their care for Ciri is one of their strongest bonds.</p></article><article class="gb-card"><span class="gb-tag">Friend and ally</span><h3>Triss Merigold</h3><p>A sorceress close to Geralt and Yennefer. She helps Ciri at Kaer Morhen and has a significant role in the games.</p></article><article class="gb-card"><span class="gb-tag">Friend and storyteller</span><h3>Dandelion</h3><p>A poet and bard who shares Geralt’s travels. His ballads turn the witcher’s adventures into legends.</p></article><article class="gb-card"><span class="gb-tag">Mentor</span><h3>Vesemir</h3><p>An experienced witcher of Kaer Morhen and Geralt’s teacher. He connects Geralt to the stronghold, his school, and his fellow witchers.</p></article></div></section>
<section id="games"><h2>The story continues in the games</h2><p>CD PROJEKT RED’s games present their own continuation of the books. Player choices affect relationships and outcomes.</p><details><summary>Show the three game premises · mild spoilers</summary><div class="gb-games"><article><h3>The Witcher</h3><p>Geralt returns with his memory lost. Looking for answers draws him into conflicts shaped by competing interests.</p></article><article><h3>The Witcher 2: Assassins of Kings</h3><p>The witcher becomes caught in a political crisis. He must investigate the deaths of rulers while trying to recover his past.</p></article><article><h3>The Witcher 3: Wild Hunt</h3><p>The search for Ciri takes Geralt through war-torn lands. Family, old connections, and the threat of the Wild Hunt take centre stage.</p></article></div></details><a class="gb-cta" href="gallery.php">Explore the gallery</a><div class="gb-source">More about the world and characters: <a href="https://www.thewitcher.com/">The Witcher</a> · <a href="https://en.wikipedia.org/wiki/The_Witcher">The Witcher — books</a></div></section></main><?php endif; ?><footer><p><?= htmlspecialchars($lang['footer_text']) ?></p></footer></body></html>
